from tkinter import *
root = Tk()
root.title("Calculator")
root.minsize(500,450)
root.resizable(0,0)
root.configure(background="skyblue")
a = StringVar()
def show(c):
    a.set(a.get()+c)
def solve():
    eq = a.get()
    a.set(eval(eq))
def clr():
    a.set("")
e1 = Entry(font=("",40),justify="right",textvariable=a)
e1.place(x=0,y=0,width=500,height=80)

b1 = Button(text="7",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b1.place(x=5,y=85,width=100,height=50)
b1.configure(command=lambda:show("7"))
b2 = Button(text="8",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b2.place(x=110,y=85,width=100,height=50)
b2.configure(command=lambda:show("8"))
b3 = Button(text="9",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b3.place(x=215,y=85,width=100,height=50)
b3.configure(command=lambda:show("9"))
b4 = Button(text="+",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b4.place(x=320,y=85,width=100,height=50)
b4.configure(command=lambda:show("+"))

b5 = Button(text="4",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b5.place(x=5,y=140,width=100,height=50)
b5.configure(command=lambda:show("4"))
b6 = Button(text="5",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b6.place(x=110,y=140,width=100,height=50)
b6.configure(command=lambda:show("5"))
b7 = Button(text="6",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b7.place(x=215,y=140,width=100,height=50)
b7.configure(command=lambda:show("6"))
b8 = Button(text="-",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b8.place(x=320,y=140,width=100,height=50)
b8.configure(command=lambda:show("-"))

b9 = Button(text="1",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b9.place(x=5,y=195,width=100,height=50)
b9.configure(command=lambda:show("1"))
b10 = Button(text="2",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b10.place(x=110,y=195,width=100,height=50)
b10.configure(command=lambda:show("2"))
b11 = Button(text="3",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b11.place(x=215,y=195,width=100,height=50)
b11.configure(command=lambda:show("3"))
b12 = Button(text="*",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b12.place(x=320,y=195,width=100,height=50)
b12.configure(command=lambda:show("*"))

b13 = Button(text="C",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b13.place(x=5,y=250,width=100,height=50)
b13.configure(command=clr)
b14 = Button(text="0",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b14.place(x=110,y=250,width=100,height=50)
b14.configure(command=lambda:show("0"))
b15 = Button(text="=",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b15.place(x=215,y=250,width=100,height=50)
b15.configure(command=solve)
b16 = Button(text="/",font=("",20),bg="gray",fg="white",activebackground="red",activeforeground="yellow")
b16.place(x=320,y=250,width=100,height=50)
b16.configure(command=lambda:show("/"))


root.mainloop()